/**
 * Dashboard Example - Generated by Shadcn Designer Skill
 *
 * This example demonstrates how to create a comprehensive dashboard layout
 * using the shadcn-designer skill with ultrathink design principles.
 */

import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import {
  BarChart3,
  Users,
  TrendingUp,
  DollarSign,
  Activity,
  Download,
  Settings,
  Bell
} from 'lucide-react';

export function DashboardExample() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b">
        <div className="flex h-16 items-center px-6">
          <div className="flex items-center space-x-4">
            <BarChart3 className="h-6 w-6" />
            <h1 className="text-xl font-semibold">Analytics Dashboard</h1>
          </div>
          <div className="ml-auto flex items-center space-x-4">
            <Button variant="outline" size="sm">
              <Bell className="h-4 w-4 mr-2" />
              Notifications
            </Button>
            <Button variant="outline" size="sm">
              <Settings className="h-4 w-4 mr-2" />
              Settings
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="p-6">
        {/* KPI Cards */}
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4 mb-8">
          <KPICard
            title="Total Revenue"
            value="$45,231"
            change="+12.5%"
            changeType="positive"
            icon={DollarSign}
          />
          <KPICard
            title="Active Users"
            value="2,543"
            change="+8.2%"
            changeType="positive"
            icon={Users}
          />
          <KPICard
            title="Conversion Rate"
            value="3.24%"
            change="-2.1%"
            changeType="negative"
            icon={TrendingUp}
          />
          <KPICard
            title="Server Load"
            value="67%"
            change="Stable"
            changeType="neutral"
            icon={Activity}
          />
        </div>

        {/* Charts and Tables */}
        <Tabs defaultValue="overview" className="space-y-6">
          <TabsList>
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="analytics">Analytics</TabsTrigger>
            <TabsTrigger value="reports">Reports</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="space-y-6">
            <div className="grid gap-6 lg:grid-cols-2">
              {/* Revenue Chart Placeholder */}
              <Card>
                <CardHeader>
                  <CardTitle>Revenue Overview</CardTitle>
                  <CardDescription>Monthly revenue trends</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="h-[200px] flex items-center justify-center bg-muted/20 rounded-md">
                    <BarChart3 className="h-8 w-8 text-muted-foreground" />
                    <span className="ml-2 text-muted-foreground">Chart Component</span>
                  </div>
                </CardContent>
              </Card>

              {/* User Activity */}
              <Card>
                <CardHeader>
                  <CardTitle>User Activity</CardTitle>
                  <CardDescription>Recent user engagement</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {userActivityData.map((activity, index) => (
                      <div key={index} className="flex items-center justify-between">
                        <div className="flex items-center space-x-3">
                          <div className="h-2 w-2 bg-primary rounded-full"></div>
                          <span className="text-sm">{activity.action}</span>
                        </div>
                        <Badge variant="secondary">{activity.count}</Badge>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="analytics" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Performance Metrics</CardTitle>
                <CardDescription>System performance over time</CardDescription>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Metric</TableHead>
                      <TableHead>Current</TableHead>
                      <TableHead>Target</TableHead>
                      <TableHead>Status</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {performanceMetrics.map((metric, index) => (
                      <TableRow key={index}>
                        <TableCell className="font-medium">{metric.name}</TableCell>
                        <TableCell>{metric.current}</TableCell>
                        <TableCell>{metric.target}</TableCell>
                        <TableCell>
                          <Badge
                            variant={metric.status === 'good' ? 'default' :
                                     metric.status === 'warning' ? 'secondary' : 'destructive'}
                          >
                            {metric.status}
                          </Badge>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="reports" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Export Reports</CardTitle>
                <CardDescription>Download detailed reports in various formats</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4 md:grid-cols-3">
                  {reportTypes.map((report, index) => (
                    <div key={index} className="flex items-center justify-between p-4 border rounded-lg">
                      <div>
                        <h4 className="font-medium">{report.name}</h4>
                        <p className="text-sm text-muted-foreground">{report.description}</p>
                      </div>
                      <Button size="sm" variant="outline">
                        <Download className="h-4 w-4 mr-2" />
                        Export
                      </Button>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </main>
    </div>
  );
}

// KPI Card Component
interface KPICardProps {
  title: string;
  value: string;
  change: string;
  changeType: 'positive' | 'negative' | 'neutral';
  icon: React.ComponentType<{ className?: string }>;
}

function KPICard({ title, value, change, changeType, icon: Icon }: KPICardProps) {
  const changeColor = changeType === 'positive' ? 'text-green-600' :
                     changeType === 'negative' ? 'text-red-600' : 'text-gray-600';

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm font-medium">{title}</CardTitle>
        <Icon className="h-4 w-4 text-muted-foreground" />
      </CardHeader>
      <CardContent>
        <div className="text-2xl font-bold">{value}</div>
        <p className={`text-xs ${changeColor}`}>
          {change}
        </p>
      </CardContent>
    </Card>
  );
}

// Mock data
const userActivityData = [
  { action: "Page Views", count: "1,234" },
  { action: "Button Clicks", count: "456" },
  { action: "Form Submissions", count: "89" },
  { action: "Downloads", count: "23" }
];

const performanceMetrics = [
  { name: "Page Load Time", current: "1.2s", target: "<2s", status: "good" },
  { name: "Server Response", current: "245ms", target: "<300ms", status: "good" },
  { name: "Error Rate", current: "0.1%", target: "<1%", status: "good" },
  { name: "Uptime", current: "99.9%", target: ">99%", status: "good" }
];

const reportTypes = [
  {
    name: "Monthly Report",
    description: "Comprehensive monthly analytics"
  },
  {
    name: "User Report",
    description: "User behavior and demographics"
  },
  {
    name: "Performance Report",
    description: "System performance metrics"
  }
];

export default DashboardExample;