#!/bin/bash
# =============================================================================
# sync-config.sh — Sync local Claude Code config into repo for Docker image
# =============================================================================
# Run this on your laptop when you add/change agents, skills, commands, or
# other Claude Code config. Changes are then committed and deployed to Hetzner.
#
# What gets synced:
#   ~/.claude/agents/       → config/.claude/agents/
#   ~/.claude/skills/       → config/.claude/skills/
#   ~/.claude/commands/     → config/.claude/commands/
#   ~/.claude/rules/        → config/.claude/rules/
#   ~/.claude/keybindings.json → config/.claude/keybindings.json
#
# What does NOT get synced (must stay manual):
#   settings.json  — adapted for container (no host-specific paths)
#   .credentials.json — secrets, never committed
#   .claude.json   — generated by entrypoint
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_DIR="$REPO_DIR/config/.claude"
LOCAL_DIR="${HOME}/.claude"

# Colors
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()    { echo -e "${CYAN}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }

echo "================================================================"
echo "  Sync Claude Code config → Docker image"
echo "================================================================"

if [ ! -d "$LOCAL_DIR" ]; then
    echo "Error: $LOCAL_DIR not found"
    exit 1
fi

# Sync agents
if [ -d "$LOCAL_DIR/agents" ]; then
    log_info "Syncing agents..."
    rm -rf "$CONFIG_DIR/agents"
    cp -r "$LOCAL_DIR/agents" "$CONFIG_DIR/agents"
    count=$(find "$CONFIG_DIR/agents" -name "*.md" | wc -l)
    log_success "  $count agent(s) synced"
fi

# Sync skills
if [ -d "$LOCAL_DIR/skills" ]; then
    log_info "Syncing skills..."
    rm -rf "$CONFIG_DIR/skills"
    cp -r "$LOCAL_DIR/skills" "$CONFIG_DIR/skills"
    count=$(find "$CONFIG_DIR/skills" -mindepth 1 -maxdepth 1 -type d | wc -l)
    log_success "  $count skill(s) synced"
fi

# Sync commands
if [ -d "$LOCAL_DIR/commands" ]; then
    log_info "Syncing commands..."
    rm -rf "$CONFIG_DIR/commands"
    cp -r "$LOCAL_DIR/commands" "$CONFIG_DIR/commands"
    count=$(find "$CONFIG_DIR/commands" -name "*.md" | wc -l)
    log_success "  $count command(s) synced"
fi

# Sync rules
if [ -d "$LOCAL_DIR/rules" ]; then
    log_info "Syncing rules..."
    rm -rf "$CONFIG_DIR/rules"
    cp -r "$LOCAL_DIR/rules" "$CONFIG_DIR/rules"
    count=$(find "$CONFIG_DIR/rules" -name "*.md" | wc -l)
    log_success "  $count rule(s) synced"
fi

# Sync keybindings
if [ -f "$LOCAL_DIR/keybindings.json" ]; then
    log_info "Syncing keybindings..."
    cp "$LOCAL_DIR/keybindings.json" "$CONFIG_DIR/keybindings.json"
    log_success "  keybindings.json synced"
fi

# Show what's in settings.json (reminder to update manually if needed)
echo ""
log_warn "settings.json is NOT auto-synced (container-adapted version)."
log_warn "If you changed plugins/hooks locally, update config/.claude/settings.json manually."

echo ""
echo "================================================================"
log_success "Sync complete. Commit and deploy to Hetzner."
echo "================================================================"
